### ISSUE TITLE
Apple Developers 登録

### ISSUE THREAD

**Issue by a-sueki** [a-sueki/sample003#104]
https://developer.apple.com/jp/support/enrollment/

**Comment by t-shimizu-aligns** [comment]
登録できました。
Your Enrollment ID: SL2F74V5Y7

しばらく先方の手続き待ちのようです（↓）
登録情報がApple Developer Supportによって確認され、次の手順に関するEメールが届き次第、ライセンス契約の確認およびメンバーシップの購入を行うことが可能になります。

**Comment by a-sueki** [comment]
ありがとうございます！

**Comment by t-shimizu-aligns** [comment]
使えるようになりました。
https://developer.apple.com/account/#/overview/8XHYKA9AWM
APPLE ID: tys.shimizu@gmail.com
PWD: GCPと同じ
