### ISSUE TITLE
Dashboard画面のレイアウトレビュー

### ISSUE THREAD

**Issue by a-sueki** [a-sueki/sample003#20]

**Comment by a-sueki** [comment]
数値とか項目は適当です。
デモで表示したい項目があれば教えてください。

![スクリーンショット 2019-03-29 13 14 19](https://user-images.githubusercontent.com/27991083/55209185-a0b49400-5224-11e9-8f0d-6ef2b1ee20ab.png)
![スクリーンショット 2019-03-29 13 15 18](https://user-images.githubusercontent.com/27991083/55209201-b5912780-5224-11e9-89a7-cec23026a902.png)

**Comment by t-shimizu-aligns** [comment]
写真・動画を共有する項目が欲しいです。
「新商品の陳列方法の共有」とかというタイトルで。
※チャットからトップにUPする、逆もできるようにしたいです。
![陳列写真](https://user-images.githubusercontent.com/49050828/55209952-65b45f80-5228-11e9-8863-8e5b35e76c86.jpg)

**Comment by t-shimizu-aligns** [comment]
あと、プロジェクト管理（又は、シフト管理、スケジュール表）的なものも見せたいです。
※探したけど、スマホで気が利いたViewが出せるツールってあまり無いみたい。
![工程表](https://user-images.githubusercontent.com/49050828/55214745-e8461a80-523a-11e9-8209-db058c988ed0.jpg)
