### ISSUE TITLE
画面遷移図を作成する(ver1.0)

### ISSUE THREAD

**Issue by a-sueki** [a-sueki/sample003#24]

**Comment by a-sueki** [comment]
https://drive.google.com/file/d/19IWY_FNVjKKsSSYIlMEm2menQ9fDMxSW/view?usp=sharing

**Comment by a-sueki** [comment]
![Align_SampleApp画面遷移図-Group Chat](https://user-images.githubusercontent.com/27991083/55667945-e238e500-589d-11e9-913b-34ea9df6be7b.jpg)
![Align_SampleApp画面遷移図-Home](https://user-images.githubusercontent.com/27991083/55667946-e2d17b80-589d-11e9-81f5-118a8f89434e.jpg)

**Comment by a-sueki** [comment]
SETTINGがまだですが、いったん確認していただればと思います。

**Comment by a-sueki** [comment]
ちょっと直し＆追加。

**■Home**
![Align_SampleApp画面遷移図-Home](https://user-images.githubusercontent.com/27991083/55706080-40d79d80-5a1b-11e9-87aa-52cb59211036.jpg)

**■Group Chat**
![Align_SampleApp画面遷移図-Group Chat](https://user-images.githubusercontent.com/27991083/55706156-74b2c300-5a1b-11e9-8843-588f41e7cd6e.jpg)

**■Setting**
![Align_SampleApp画面遷移図-Setting](https://user-images.githubusercontent.com/27991083/55706167-7b413a80-5a1b-11e9-95d4-2612396713f1.jpg)

**■Signup/Login**
![Align_SampleApp画面遷移図-Sign up _  Log in](https://user-images.githubusercontent.com/27991083/55706182-83997580-5a1b-11e9-8467-58846eaaca2a.jpg)

**Comment by t-shimizu-aligns** [comment]
まずはHomeの最初にもらったVersionのみ確認しましたので、コメント入りを添付しますね。
![画面遷移_home_20190408清水](https://user-images.githubusercontent.com/49050828/55707822-7c746680-5a1f-11e9-9b7f-f8db6827b3d3.jpg)
