### ISSUE TITLE
Alignsのサービス用アカウントを作成する

### ISSUE THREAD

**Issue by a-sueki** [a-sueki/sample003#85]

**Comment by t-shimizu-aligns** [comment]
gcpのアカウントっていうのが正直よくわかってないのですが、
・私のalignsメールに紐づくgcpを用意
・プロジェクト「dataplatform2019」を作成
・これに、末岐さんalignsメールをオーナー権限で追加

これでだめでしょうかね？今アクセスできる状態かと思います。
まだカードを登録していないので、上記でOKであればカード登録しようと思います。

**Comment by a-sueki** [comment]
とりあえずはFirebaseに登録する用のメールアドレス（{service名}@alings.co.jpみたいな）が欲しいだけです。
そのメールアドレスでFirebaseにサインアップして、請求情報などは別途清水さんに入力していただく流れです。

もちろん、ご記載いただいたgcpアカウントは、後々MLなどの拡張で必要になるので作っていただいて問題ないです。

**Comment by a-sueki** [comment]
あ、もうFirebaseのアカウントも作ってくれたんですね！ありがとうございます。

**Comment by t-shimizu-aligns** [comment]
これではだめ？
・私のalignsメールに紐づく**firebase**を用意
・プロジェクト「dataplatform2019」を作成
・これに、末岐さんalignsメールをオーナー権限で追加

違ってても怒らないでね・・・

**Comment by a-sueki** [comment]
完璧です！ありがとうございます！
